apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-appa/b   # Select both Version A and B
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # The service will load-balance between all matching pods (Version A and B)